/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../node_modules/primeng/components/chart/chart.ngfactory';
import * as i2 from 'primeng/components/chart/chart';
import * as i3 from './chart.component';
const styles_ChartComponent:any[] = ([] as any[]);
export const RenderType_ChartComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ChartComponent,data:{}});
export function View_ChartComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),1,'p-chart',([] as any[]),(null as any),(null as any),
      (null as any),i1.View_UIChart_0,i1.RenderType_UIChart)),i0.ɵdid(4374528,(null as any),
      0,i2.UIChart,[i0.ElementRef],{type:[0,'type'],options:[1,'options'],data:[2,
          'data']},(null as any)),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,
      _v) => {
    var _co:i3.ChartComponent = _v.component;
    const currVal_0:any = _co.type;
    const currVal_1:any = _co.options;
    const currVal_2:any = _co.data;
    _ck(_v,2,0,currVal_0,currVal_1,currVal_2);
  },(null as any));
}
export function View_ChartComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-chart',([] as any[]),
      (null as any),(null as any),(null as any),View_ChartComponent_0,RenderType_ChartComponent)),
      i0.ɵdid(49152,(null as any),0,i3.ChartComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ChartComponentNgFactory:i0.ComponentFactory<i3.ChartComponent> = i0.ɵccf('app-chart',
    i3.ChartComponent,View_ChartComponent_Host_0,{data:'data',options:'options',type:'type'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvY2hhcnQvY2hhcnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2M6L1VzZXJzL3phMzEyNTgzL0RvY3VtZW50cy9HaXQvQ3VzdG9tZXItVHJhY2tlci9hc3NldHMvYXBwL2NoYXJ0L2NoYXJ0LmNvbXBvbmVudC50cyIsIm5nOi8vL2M6L1VzZXJzL3phMzEyNTgzL0RvY3VtZW50cy9HaXQvQ3VzdG9tZXItVHJhY2tlci9hc3NldHMvYXBwL2NoYXJ0L2NoYXJ0LmNvbXBvbmVudC50cy5DaGFydENvbXBvbmVudC5odG1sIiwibmc6Ly8vYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvY2hhcnQvY2hhcnQuY29tcG9uZW50LnRzLkNoYXJ0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxwLWNoYXJ0IFt0eXBlXT1cInR5cGVcIiBbb3B0aW9uc109XCJvcHRpb25zXCIgW2RhdGFdPVwiZGF0YVwiPjwvcC1jaGFydD5cbiAgICAiLCI8YXBwLWNoYXJ0PjwvYXBwLWNoYXJ0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBLCtEQUFBO01BQUE7VUFBQSx3QkFBbUU7OztJQUExRDtJQUFjO0lBQW9CO0lBQTNDLFdBQVMsVUFBYyxVQUFvQixTQUEzQzs7OztvQkNEUjtNQUFBO2FBQUE7VUFBQTs7OzsifQ==
