/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './error.component';
import * as i2 from '../../../node_modules/primeng/components/growl/growl.ngfactory';
import * as i3 from 'primeng/components/dom/domhandler';
import * as i4 from 'primeng/components/growl/growl';
import * as i5 from './error.service';
const styles_ErrorComponent:any[] = ([] as any[]);
export const RenderType_ErrorComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ErrorComponent,data:{}});
export function View_ErrorComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'p-growl',([] as any[]),(null as any),[[(null as any),
          'valueChange']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.ErrorComponent = _v.component;
        if (('valueChange' === en)) {
          const pd_0:any = ((<any>(_co.msgs = $event)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },i2.View_Growl_0,i2.RenderType_Growl)),i0.ɵprd(512,(null as any),i3.DomHandler,
      i3.DomHandler,([] as any[])),i0.ɵdid(4636672,(null as any),0,i4.Growl,[i0.ElementRef,
      i3.DomHandler,i0.IterableDiffers],{value:[0,'value']},{valueChange:'valueChange'}),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i1.ErrorComponent = _v.component;
    const currVal_0:any = _co.msgs;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_ErrorComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-error',([] as any[]),
      (null as any),(null as any),(null as any),View_ErrorComponent_0,RenderType_ErrorComponent)),
      i0.ɵdid(114688,(null as any),0,i1.ErrorComponent,[i5.ErrorService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ErrorComponentNgFactory:i0.ComponentFactory<i1.ErrorComponent> = i0.ɵccf('app-error',
    i1.ErrorComponent,View_ErrorComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvZXJyb3IvZXJyb3IuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2M6L1VzZXJzL3phMzEyNTgzL0RvY3VtZW50cy9HaXQvQ3VzdG9tZXItVHJhY2tlci9hc3NldHMvYXBwL2Vycm9yL2Vycm9yLmNvbXBvbmVudC50cyIsIm5nOi8vL2M6L1VzZXJzL3phMzEyNTgzL0RvY3VtZW50cy9HaXQvQ3VzdG9tZXItVHJhY2tlci9hc3NldHMvYXBwL2Vycm9yL2Vycm9yLmNvbXBvbmVudC50cy5FcnJvckNvbXBvbmVudC5odG1sIiwibmc6Ly8vYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvZXJyb3IvZXJyb3IuY29tcG9uZW50LnRzLkVycm9yQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxwLWdyb3dsIFsodmFsdWUpXT1cIm1zZ3NcIj48L3AtZ3Jvd2w+XG4gICAgIiwiPGFwcC1lcnJvcj48L2FwcC1lcnJvcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtVQUFBO1FBQUE7UUFBQTtRQUFTO1VBQUE7VUFBQTtRQUFBO1FBQVQ7TUFBQTtvQkFBQSxzQkFBQTtzQ0FBQTtNQUFvQzs7SUFBM0I7SUFBVCxXQUFTLFNBQVQ7Ozs7b0JDRFI7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
