/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
import * as i2 from 'primeng/components/dom/domhandler';
import * as i3 from 'primeng/components/button/button';
import * as i4 from './auth.service';
import * as i5 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'button',[['icon','fa-sign-out'],['label','Logout'],
          ['pButton',''],['type','button']],(null as any),[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.LogoutComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onLogout()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵprd(512,(null as any),i2.DomHandler,i2.DomHandler,
      ([] as any[])),i0.ɵdid(4341760,(null as any),0,i3.Button,[i0.ElementRef,i2.DomHandler],
      {label:[0,'label'],icon:[1,'icon']},(null as any)),(_l()(),i0.ɵted((null as any),
      ['\n    ']))],(_ck,_v) => {
    const currVal_0:any = 'Logout';
    const currVal_1:any = 'fa-sign-out';
    _ck(_v,3,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),
      (null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
      i0.ɵdid(49152,(null as any),0,i1.LogoutComponent,[i4.AuthService,i5.Router],
          (null as any),(null as any))],(null as any),(null as any));
}
export const LogoutComponentNgFactory:i0.ComponentFactory<i1.LogoutComponent> = i0.ɵccf('app-logout',
    i1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2M6L1VzZXJzL3phMzEyNTgzL0RvY3VtZW50cy9HaXQvQ3VzdG9tZXItVHJhY2tlci9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL2M6L1VzZXJzL3phMzEyNTgzL0RvY3VtZW50cy9HaXQvQ3VzdG9tZXItVHJhY2tlci9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL2M6L1VzZXJzL3phMzEyNTgzL0RvY3VtZW50cy9HaXQvQ3VzdG9tZXItVHJhY2tlci9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGJ1dHRvbiBwQnV0dG9uIHR5cGU9XCJidXR0b25cIiBwQnV0dG9uIGljb249XCJmYS1zaWduLW91dFwiIChjbGljayk9XCJvbkxvZ291dCgpXCIgbGFiZWw9XCJMb2dvdXRcIj48L2J1dHRvbj5cbiAgICAiLCI8YXBwLWxvZ291dD48L2FwcC1sb2dvdXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLCtDQUNRO01BQUE7VUFBQTtNQUFBO1FBQUE7UUFBQTtRQUF5RDtVQUFBO1VBQUE7UUFBQTtRQUF6RDtNQUFBO01BQUEsc0JBQUE7TUFBQSxtREFBc0c7TUFBQTtJQUF4QjtJQUF4QztJQUF0QyxXQUE4RSxVQUF4QyxTQUF0Qzs7OztvQkNEUjtNQUFBO2FBQUE7VUFBQTs7OyJ9
