/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './customer.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from './customer.service';
import * as i5 from '@angular/http';
import * as i6 from '../error/error.service';
import * as i7 from 'primeng/components/inputtext/inputtext';
import * as i8 from 'primeng/components/inputtextarea/inputtextarea';
import * as i9 from 'primeng/components/common/shared';
import * as i10 from 'primeng/components/paginator/paginator';
import * as i11 from 'primeng/components/datatable/datatable';
import * as i12 from 'primeng/components/button/button';
import * as i13 from 'primeng/components/togglebutton/togglebutton';
import * as i14 from 'primeng/components/dropdown/dropdown';
import * as i15 from 'primeng/components/dialog/dialog';
import * as i16 from 'primeng/components/calendar/calendar';
import * as i17 from 'primeng/components/growl/growl';
import * as i18 from 'primeng/components/panel/panel';
import * as i19 from 'primeng/components/confirmdialog/confirmdialog';
import * as i20 from 'primeng/components/chart/chart';
export const CustomerModuleNgFactory:i0.NgModuleFactory<i1.CustomerModule> = i0.ɵcmf(i1.CustomerModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i3.FormBuilder,i3.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i4.CustomerService,i4.CustomerService,[i5.Http,i6.ErrorService]),
          i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.ɵba,
              i3.ɵba,([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),
          i0.ɵmpd(512,i3.ReactiveFormsModule,i3.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i7.InputTextModule,i7.InputTextModule,([] as any[])),i0.ɵmpd(512,
              i8.InputTextareaModule,i8.InputTextareaModule,([] as any[])),i0.ɵmpd(512,
              i9.SharedModule,i9.SharedModule,([] as any[])),i0.ɵmpd(512,i10.PaginatorModule,
              i10.PaginatorModule,([] as any[])),i0.ɵmpd(512,i11.DataTableModule,i11.DataTableModule,
              ([] as any[])),i0.ɵmpd(512,i12.ButtonModule,i12.ButtonModule,([] as any[])),
          i0.ɵmpd(512,i13.ToggleButtonModule,i13.ToggleButtonModule,([] as any[])),
          i0.ɵmpd(512,i14.DropdownModule,i14.DropdownModule,([] as any[])),i0.ɵmpd(512,
              i15.DialogModule,i15.DialogModule,([] as any[])),i0.ɵmpd(512,i16.CalendarModule,
              i16.CalendarModule,([] as any[])),i0.ɵmpd(512,i17.GrowlModule,i17.GrowlModule,
              ([] as any[])),i0.ɵmpd(512,i18.PanelModule,i18.PanelModule,([] as any[])),
          i0.ɵmpd(512,i19.ConfirmDialogModule,i19.ConfirmDialogModule,([] as any[])),
          i0.ɵmpd(512,i20.ChartModule,i20.ChartModule,([] as any[])),i0.ɵmpd(512,i1.CustomerModule,
              i1.CustomerModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvY3VzdG9tZXJzL2N1c3RvbWVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9jOi9Vc2Vycy96YTMxMjU4My9Eb2N1bWVudHMvR2l0L0N1c3RvbWVyLVRyYWNrZXIvYXNzZXRzL2FwcC9jdXN0b21lcnMvY3VzdG9tZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
