/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './customers/customer.component.ngfactory';
import * as i4 from './auth/authentication.component.ngfactory';
import * as i5 from './auth/signup.component.ngfactory';
import * as i6 from './auth/logout.component.ngfactory';
import * as i7 from './info/info.component.ngfactory';
import * as i8 from './app.component.ngfactory';
import * as i9 from '@angular/common';
import * as i10 from '@angular/platform-browser';
import * as i11 from '@angular/animations/browser';
import * as i12 from '@angular/platform-browser/animations';
import * as i13 from '@angular/animations';
import * as i14 from '@angular/forms';
import * as i15 from '@angular/http';
import * as i16 from './error/error.service';
import * as i17 from './customers/customer.service';
import * as i18 from '@angular/router';
import * as i19 from './auth/auth.service';
import * as i20 from './customers/customer.component';
import * as i21 from './auth/authentication.component';
import * as i22 from './auth/signup.component';
import * as i23 from './auth/logout.component';
import * as i24 from './info/info.component';
import * as i25 from 'primeng/components/inputtext/inputtext';
import * as i26 from 'primeng/components/button/button';
import * as i27 from 'primeng/components/togglebutton/togglebutton';
import * as i28 from 'primeng/components/common/shared';
import * as i29 from 'primeng/components/dropdown/dropdown';
import * as i30 from 'primeng/components/tabmenu/tabmenu';
import * as i31 from 'primeng/components/password/password';
import * as i32 from 'primeng/components/growl/growl';
import * as i33 from 'primeng/components/panel/panel';
import * as i34 from 'primeng/components/confirmdialog/confirmdialog';
import * as i35 from 'primeng/components/inputtextarea/inputtextarea';
import * as i36 from 'primeng/components/paginator/paginator';
import * as i37 from 'primeng/components/datatable/datatable';
import * as i38 from 'primeng/components/dialog/dialog';
import * as i39 from 'primeng/components/calendar/calendar';
import * as i40 from 'primeng/components/chart/chart';
import * as i41 from './customers/customer.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.CustomerComponentNgFactory,i4.AuthenticationComponentNgFactory,i5.SignupComponentNgFactory,
              i6.LogoutComponentNgFactory,i7.InfoComponentNgFactory,i8.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i9.NgLocalization,i9.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i10.DomSanitizer,i10.ɵe,[i9.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i10.DomSanitizer]),i0.ɵmpd(4608,
              i10.HAMMER_GESTURE_CONFIG,i10.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i10.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i10.ɵDomEventsPlugin(p0_0),new i10.ɵKeyEventsPlugin(p1_0),
                    new i10.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i9.DOCUMENT,i9.DOCUMENT,i9.DOCUMENT,i10.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i10.EventManager,i10.EventManager,[i10.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i10.ɵDomSharedStylesHost,i10.ɵDomSharedStylesHost,[i9.DOCUMENT]),
          i0.ɵmpd(4608,i10.ɵDomRendererFactory2,i10.ɵDomRendererFactory2,[i10.EventManager,
              i10.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i11.AnimationDriver,i12.ɵc,([] as any[])),
          i0.ɵmpd(5120,i11.ɵAnimationStyleNormalizer,i12.ɵd,([] as any[])),i0.ɵmpd(4608,
              i11.ɵAnimationEngine,i12.ɵb,[i11.AnimationDriver,i11.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i12.ɵe,[i10.ɵDomRendererFactory2,i11.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i10.ɵSharedStylesHost,(null as any),[i10.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i10.Meta,
              i10.Meta,[i9.DOCUMENT]),i0.ɵmpd(4608,i10.Title,i10.Title,[i9.DOCUMENT]),
          i0.ɵmpd(4608,i13.AnimationBuilder,i12.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i14.ɵi,i14.ɵi,([] as any[])),i0.ɵmpd(4608,i14.FormBuilder,i14.FormBuilder,
              ([] as any[])),i0.ɵmpd(4608,i15.BrowserXhr,i15.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i15.ResponseOptions,i15.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i15.XSRFStrategy,i15.ɵb,([] as any[])),i0.ɵmpd(4608,i15.XHRBackend,
              i15.XHRBackend,[i15.BrowserXhr,i15.ResponseOptions,i15.XSRFStrategy]),
          i0.ɵmpd(4608,i15.RequestOptions,i15.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i15.Http,i15.ɵc,[i15.XHRBackend,i15.RequestOptions]),i0.ɵmpd(4608,i16.ErrorService,
              i16.ErrorService,([] as any[])),i0.ɵmpd(4608,i17.CustomerService,i17.CustomerService,
              [i15.Http,i16.ErrorService]),i0.ɵmpd(5120,i18.ActivatedRoute,i18.ɵf,
              [i18.Router]),i0.ɵmpd(4608,i18.NoPreloading,i18.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i18.PreloadingStrategy,(null as any),[i18.NoPreloading]),i0.ɵmpd(135680,
              i18.RouterPreloader,i18.RouterPreloader,[i18.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i18.PreloadingStrategy]),i0.ɵmpd(4608,i18.PreloadAllModules,
              i18.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i18.ROUTER_INITIALIZER,
              i18.ɵi,[i18.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i18.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i19.AuthService,i19.AuthService,
              [i15.Http,i16.ErrorService]),i0.ɵmpd(512,i9.CommonModule,i9.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i10.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i18.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i18.ɵg,i18.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i10.ɵc(p0_0,p0_1),i18.ɵh(p1_0)];
              },[[2,i10.NgProbeToken],[2,i0.NgProbeToken],i18.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i10.BrowserModule,i10.BrowserModule,[[3,i10.BrowserModule]]),
          i0.ɵmpd(512,i12.BrowserAnimationsModule,i12.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i14.ɵba,i14.ɵba,([] as any[])),i0.ɵmpd(512,i14.FormsModule,i14.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i14.ReactiveFormsModule,i14.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i15.HttpModule,i15.HttpModule,([] as any[])),
          i0.ɵmpd(1024,i18.ɵa,i18.ɵd,[[3,i18.Router]]),i0.ɵmpd(512,i18.UrlSerializer,
              i18.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i18.ChildrenOutletContexts,
              i18.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i18.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i9.LocationStrategy,i18.ɵc,[i9.PlatformLocation,
              [2,i9.APP_BASE_HREF],i18.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i9.Location,
              i9.Location,[i9.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i18.ROUTES,
              () => {
                return [[{path:'',redirectTo:'/customers',pathMatch:'full'},{path:'customers',
                    component:i20.CustomerComponent},{path:'auth',component:i21.AuthenticationComponent,
                    children:[{path:'',component:i21.AuthenticationComponent,pathMatch:'full'},
                        {path:'signup',component:i22.SignupComponent},{path:'signin',
                            component:i22.SignupComponent},{path:'logout',component:i23.LogoutComponent}]},
                    {path:'info',component:i24.InfoComponent,children:[{path:'',component:i24.InfoComponent,
                        pathMatch:'full'}]}]];
              },([] as any[])),i0.ɵmpd(1024,i18.Router,i18.ɵe,[i0.ApplicationRef,i18.UrlSerializer,
              i18.ChildrenOutletContexts,i9.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i18.ROUTES,i18.ROUTER_CONFIGURATION,[2,i18.UrlHandlingStrategy],
              [2,i18.RouteReuseStrategy]]),i0.ɵmpd(512,i18.RouterModule,i18.RouterModule,
              [[2,i18.ɵa],[2,i18.Router]]),i0.ɵmpd(512,i25.InputTextModule,i25.InputTextModule,
              ([] as any[])),i0.ɵmpd(512,i26.ButtonModule,i26.ButtonModule,([] as any[])),
          i0.ɵmpd(512,i27.ToggleButtonModule,i27.ToggleButtonModule,([] as any[])),
          i0.ɵmpd(512,i28.SharedModule,i28.SharedModule,([] as any[])),i0.ɵmpd(512,
              i29.DropdownModule,i29.DropdownModule,([] as any[])),i0.ɵmpd(512,i30.TabMenuModule,
              i30.TabMenuModule,([] as any[])),i0.ɵmpd(512,i31.PasswordModule,i31.PasswordModule,
              ([] as any[])),i0.ɵmpd(512,i32.GrowlModule,i32.GrowlModule,([] as any[])),
          i0.ɵmpd(512,i33.PanelModule,i33.PanelModule,([] as any[])),i0.ɵmpd(512,i34.ConfirmDialogModule,
              i34.ConfirmDialogModule,([] as any[])),i0.ɵmpd(512,i35.InputTextareaModule,
              i35.InputTextareaModule,([] as any[])),i0.ɵmpd(512,i36.PaginatorModule,
              i36.PaginatorModule,([] as any[])),i0.ɵmpd(512,i37.DataTableModule,i37.DataTableModule,
              ([] as any[])),i0.ɵmpd(512,i38.DialogModule,i38.DialogModule,([] as any[])),
          i0.ɵmpd(512,i39.CalendarModule,i39.CalendarModule,([] as any[])),i0.ɵmpd(512,
              i40.ChartModule,i40.ChartModule,([] as any[])),i0.ɵmpd(512,i41.CustomerModule,
              i41.CustomerModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9jOi9Vc2Vycy96YTMxMjU4My9Eb2N1bWVudHMvR2l0L0N1c3RvbWVyLVRyYWNrZXIvYXNzZXRzL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
