/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component.ngfactory';
import * as i2 from './header.component';
import * as i3 from './auth/auth.service';
import * as i4 from './error/error.component.ngfactory';
import * as i5 from './error/error.component';
import * as i6 from './error/error.service';
import * as i7 from '@angular/router';
import * as i8 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_HeaderComponent_0,i1.RenderType_HeaderComponent)),
      i0.ɵdid(114688,(null as any),0,i2.HeaderComponent,[i3.AuthService],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'app-error',([] as any[]),(null as any),(null as any),
          (null as any),i4.View_ErrorComponent_0,i4.RenderType_ErrorComponent)),i0.ɵdid(114688,
          (null as any),0,i5.ErrorComponent,[i6.ErrorService],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i0.ɵdid(212992,(null as any),
          0,i7.RouterOutlet,[i7.ChildrenOutletContexts,i0.ViewContainerRef,i0.ComponentFactoryResolver,
              [8,(null as any)],i0.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,4,0);
    _ck(_v,7,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i8.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i8.AppComponent> = i0.ɵccf('my-app',
    i8.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9jOi9Vc2Vycy96YTMxMjU4My9Eb2N1bWVudHMvR2l0L0N1c3RvbWVyLVRyYWNrZXIvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+XHJcbjxhcHAtZXJyb3I+PC9hcHAtZXJyb3I+XHJcbjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cclxuIiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUEsZUFBeUIsdUNBQ3pCO1VBQUE7VUFBQSw2RUFBQTtVQUFBO01BQXVCLHVDQUN2QjtVQUFBO1VBQUEsbURBQUE7VUFBQTtjQUFBO01BQStCO0lBRi9CO0lBQ0E7SUFDQTs7OztvQkNGQTtNQUFBO2FBQUE7Ozs7In0=
