/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component';
import * as i2 from '../../node_modules/primeng/components/tabmenu/tabmenu.ngfactory';
import * as i3 from 'primeng/components/dom/domhandler';
import * as i4 from 'primeng/components/tabmenu/tabmenu';
import * as i5 from './auth/auth.service';
const styles_HeaderComponent:any[] = ['#title[_ngcontent-%COMP%] {\n                text-align: center;\n                font-size: 38px;\n                letter-spacing: 3px;\n            }'];
export const RenderType_HeaderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_HeaderComponent,data:{}});
export function View_HeaderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),8,'header',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      1,'h1',[['id','title']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['Cloud TF Customer Tracker'])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          2,'p-tabMenu',([] as any[]),(null as any),[[(null as any),'modelChange']],
          (_v,en,$event) => {
            var ad:boolean = true;
            var _co:i1.HeaderComponent = _v.component;
            if (('modelChange' === en)) {
              const pd_0:any = ((<any>(_co.items = $event)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },i2.View_TabMenu_0,i2.RenderType_TabMenu)),i0.ɵprd(4608,(null as any),i3.DomHandler,
          i3.DomHandler,([] as any[])),i0.ɵdid(114688,(null as any),0,i4.TabMenu,([] as any[]),
          {model:[0,'model']},(null as any)),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i1.HeaderComponent = _v.component;
    const currVal_0:any = _co.items;
    _ck(_v,7,0,currVal_0);
  },(null as any));
}
export function View_HeaderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),View_HeaderComponent_0,RenderType_HeaderComponent)),
      i0.ɵdid(114688,(null as any),0,i1.HeaderComponent,[i5.AuthService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const HeaderComponentNgFactory:i0.ComponentFactory<i1.HeaderComponent> = i0.ɵccf('app-header',
    i1.HeaderComponent,View_HeaderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9jOi9Vc2Vycy96YTMxMjU4My9Eb2N1bWVudHMvR2l0L0N1c3RvbWVyLVRyYWNrZXIvYXNzZXRzL2FwcC9oZWFkZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vYzovVXNlcnMvemEzMTI1ODMvRG9jdW1lbnRzL0dpdC9DdXN0b21lci1UcmFja2VyL2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC50cy5IZWFkZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aGVhZGVyPlxyXG4gICAgPGgxIGlkPVwidGl0bGVcIj5DbG91ZCBURiBDdXN0b21lciBUcmFja2VyPC9oMT5cclxuICAgIDxwLXRhYk1lbnUgWyhtb2RlbCldPVwiaXRlbXNcIj48L3AtdGFiTWVudT5cclxuPC9oZWFkZXI+XHJcbiIsIjxhcHAtaGVhZGVyPjwvYXBwLWhlYWRlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBUTthQUFBLDRCQUNKO01BQUE7TUFBQSxnQkFBZTtNQUE4QiwyQ0FDN0M7VUFBQTtVQUFBO1lBQUE7WUFBQTtZQUFXO2NBQUE7Y0FBQTtZQUFBO1lBQVg7VUFBQTt3QkFBQSxzQkFBQTtVQUFBLG1DQUF5QztNQUNwQzs7SUFETTtJQUFYLFdBQVcsU0FBWDs7OztvQkNGSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
